# Generated by Django 4.2.7 on 2024-01-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rang",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
