# Generated by Django 4.2.7 on 2024-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0003_profile_rang"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rang_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="rang_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rang",
            field=models.CharField(
                blank=True, default="Silber", max_length=200, null=True
            ),
        ),
    ]
