# Generated by Django 4.2.7 on 2024-01-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0004_profile_rang_updated_at_profile_rang_valid_until_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="rang",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="rang_updated_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="rang_valid_until",
        ),
        migrations.CreateModel(
            name="Rang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "aufstieg_bei",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "abstieg_bei",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "next_rang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="higher_rang",
                        to="userauth.rang",
                    ),
                ),
                (
                    "previous_rang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lower_rang",
                        to="userauth.rang",
                    ),
                ),
            ],
        ),
    ]
