# Generated by Django 4.2.7 on 2024-01-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "userauth",
            "0005_remove_profile_rang_remove_profile_rang_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userauth.rang",
            ),
        ),
    ]
