# Generated by Django 4.2.7 on 2024-01-29 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0006_profile_rang"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_rang_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rang",
                to="userauth.rang",
            ),
        ),
    ]
