# Generated by Django 4.2.9 on 2024-03-05 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0009_abteilung_profile_abteilung'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ist_aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='toolabrechnungszyklus',
            field=models.CharField(choices=[('1', 'Monatlich'), ('3', 'Quartalsweise')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='RechnungsDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(max_length=200)),
                ('strasse', models.CharField(max_length=200)),
                ('hausnummer', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=200)),
                ('ort', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungsdaten', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
