# Generated by Django 4.2.7 on 2023-11-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_added_at", models.DateTimeField(auto_now_add=True)),
                ("deal_updated_at", models.DateTimeField(auto_now=True)),
                ("deal_closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deal_hubspotid",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("antrittsdatum", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kontakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(blank=True, max_length=200, null=True)),
                ("nachname", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("telefon", models.CharField(blank=True, max_length=200, null=True)),
                ("kontakt_added_at", models.DateTimeField(auto_now_add=True)),
                ("kontakt_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kontakt_hubspotid",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesStufe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prozente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("salesstufe_added_at", models.DateTimeField(auto_now_add=True)),
                ("salesstufe_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unternehmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("unternehmen_added_at", models.DateTimeField(auto_now_add=True)),
                ("unternehmen_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unternehmen_hubspotid",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "kontakt",
                    models.ManyToManyField(blank=True, to="billerboard.kontakt"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prozente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.deal",
                    ),
                ),
                (
                    "share_genehmigt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_genehmigt_von",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kandidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kandidat_added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "berufsbezeichnung",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "kontakt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.kontakt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Einzahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("einzahlung_added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rechnungsnummer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.deal",
                    ),
                ),
                (
                    "eingetragen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eingetragen_von",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deal",
            name="Unternehmen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billerboard.unternehmen",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="kandidat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billerboard.kandidat",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Auszahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auszahlung_added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "auszahlungstyp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEAL", "Deal"),
                            ("EINZAHLUNG", "Einzahlung"),
                            ("SONSTIGES", "Sonstiges"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ausgezahlt_an",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausgezahlt_an",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "autorisiert_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorisiert_von",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.deal",
                    ),
                ),
            ],
        ),
    ]
