# Generated by Django 4.2.7 on 2023-11-07 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billerboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prozente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("provisionlayer_added_at", models.DateTimeField(auto_now_add=True)),
                ("provisionlayer_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager_prozente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "layer_above",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.provisionlayer",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payout",
        ),
        migrations.AddField(
            model_name="deal",
            name="kulanz_bis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesstufe",
            name="revenue_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
