# Generated by Django 4.2.7 on 2023-11-20 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0003_dealdaten_incentive_deal_daten"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deal",
            old_name="Unternehmen",
            new_name="unternehmen",
        ),
    ]
