# Generated by Django 4.2.7 on 2023-11-22 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billerboard", "0004_rename_unternehmen_deal_unternehmen"),
    ]

    operations = [
        migrations.AddField(
            model_name="kontakt",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[("HERR", "Herr"), ("FRAU", "FRAU")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontakt",
            name="doer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="kontakt",
            name="eingetragen_von",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kontakt_eingetragen_von",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kontakt",
            name="position",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
