# Generated by Django 4.2.7 on 2023-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billerboard",
            "0005_kontakt_anrede_kontakt_doer_kontakt_eingetragen_von_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unternehmen",
            name="website",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
