# Generated by Django 4.2.7 on 2023-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0006_unternehmen_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="unternehmen",
            name="ort",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="unternehmen",
            name="plz",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="unternehmen",
            name="strasse_hausnummer",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="unternehmen",
            name="telefon",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),

    ]
