# Generated by Django 4.2.7 on 2023-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0007_unternehmen_ort_unternehmen_plz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unternehmen",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
