# Generated by Django 4.2.7 on 2023-12-04 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0008_alter_unternehmen_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unternehmen",
            options={"verbose_name_plural": "Unternehmen"},
        ),
        migrations.AlterUniqueTogether(
            name="unternehmen",
            unique_together={("name", "ort")},
        ),
    ]
