# Generated by Django 4.2.7 on 2023-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0009_alter_unternehmen_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unternehmen",
            name="kontakt",
        ),
        migrations.AddField(
            model_name="kontakt",
            name="ist_ansprechpartner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unternehmen",
            name="kontakte",
            field=models.ManyToManyField(
                blank=True, related_name="alle_kontakte", to="billerboard.kontakt"
            ),
        ),
    ]
