# Generated by Django 4.2.7 on 2023-12-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0011_alter_kontakt_anrede"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kontakt",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[("Herr", "Herr"), ("Frau", "Frau")],
                max_length=200,
                null=True,
            ),
        ),
    ]
