# Generated by Django 4.2.7 on 2024-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0012_alter_kontakt_anrede"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealdaten",
            name="datei",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="dealdaten",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
