# Generated by Django 4.2.7 on 2024-01-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0014_alter_deal_deal_closed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="daten",
        ),
        migrations.AddField(
            model_name="dealdaten",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billerboard.deal",
            ),
        ),
        migrations.AlterField(
            model_name="auszahlung",
            name="auszahlungstyp",
            field=models.CharField(
                blank=True,
                choices=[("DEAL", "Deal"), ("SONSTIGES", "Sonstiges")],
                max_length=200,
                null=True,
            ),
        ),
    ]
