# Generated by Django 4.2.7 on 2024-01-24 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0015_remove_deal_daten_dealdaten_deal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealdaten",
            name="dealDaten_added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dealdaten",
            name="datei",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/beweisgrundlage"
            ),
        ),
    ]
