# Generated by Django 4.2.7 on 2024-01-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0016_dealdaten_dealdaten_added_at_alter_dealdaten_datei"),
    ]

    operations = [
        migrations.AddField(
            model_name="unternehmen",
            name="ist_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unternehmen",
            name="ist_partner",
            field=models.BooleanField(default=False),
        ),
    ]
