# Generated by Django 4.2.7 on 2024-01-29 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billerboard", "0017_unternehmen_ist_blacklisted_unternehmen_ist_partner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unternehmen",
            name="ist_partner",
        ),
        migrations.CreateModel(
            name="PartnerUnternehmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("konditionen", models.TextField(blank=True, null=True)),
                (
                    "partnerunternehmen_added_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("partnerunternehmen_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partnerunternehmen_hubspotid",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "partnerunternehmen_added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerunternehmen_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partnerunternehmen_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerunternehmen_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unternehmen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerunternehmen",
                        to="billerboard.unternehmen",
                    ),
                ),
            ],
        ),
    ]
