# Generated by Django 4.2.7 on 2024-01-29 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billerboard", "0018_remove_unternehmen_ist_partner_partnerunternehmen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unternehmen",
            name="ist_blacklisted",
        ),
        migrations.CreateModel(
            name="BlacklistUnternehmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blacklist_added_at", models.DateTimeField(auto_now_add=True)),
                ("blacklist_updated_at", models.DateTimeField(auto_now=True)),
                ("grund", models.TextField(blank=True, null=True)),
                (
                    "blacklist_added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blacklist_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unternehmen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklistunternehmen",
                        to="billerboard.unternehmen",
                    ),
                ),
            ],
        ),
    ]
