# Generated by Django 4.2.7 on 2024-01-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0019_remove_unternehmen_ist_blacklisted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share",
                to="billerboard.deal",
            ),
        ),
    ]
