# Generated by Django 4.2.9 on 2024-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0020_alter_share_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdaten',
            name='name',
            field=models.CharField(choices=[('AGB', 'AGB'), ('DSGVO', 'DSGVO'), ('VERTRAG', 'Vertrag'), ('SONSTIGES', 'Sonstiges')], max_length=200),
        ),
    ]
