# Generated by Django 4.2.9 on 2024-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0021_alter_dealdaten_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdaten',
            name='name',
            field=models.CharField(choices=[('AGB', 'AGB vom Kunden'), ('DSGVO', 'DSGVO vom Kandidaten'), ('VERTRAG', 'Vertrag unterschrieben von beiden Parteien'), ('SONSTIGES', 'Sonstiges')], max_length=200),
        ),
    ]
