# Generated by Django 4.2.9 on 2024-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0022_alter_dealdaten_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umsatzziel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
