# Generated by Django 4.2.9 on 2024-02-21 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0023_umsatzziel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv1', models.IntegerField(blank=True, null=True)),
                ('iv2', models.IntegerField(blank=True, null=True)),
                ('iv3', models.IntegerField(blank=True, null=True)),
                ('final', models.IntegerField(blank=True, null=True)),
                ('offer', models.IntegerField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
