# Generated by Django 4.2.9 on 2024-02-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0024_ivboardentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IvBoardEntry',
        ),
    ]
