# Generated by Django 4.2.9 on 2024-02-26 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0025_delete_ivboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('kandidat', 'unternehmen')},
        ),
        migrations.CreateModel(
            name='InterviewBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv_this_week', models.IntegerField(blank=True, default=0, null=True)),
                ('iv_next_week', models.IntegerField(blank=True, default=0, null=True)),
                ('offer', models.IntegerField(blank=True, default=0, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billerboard.interviewboard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'board')},
            },
        ),
    ]
