# Generated by Django 4.2.9 on 2024-02-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0027_interviewboard_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewboardentry',
            unique_together=set(),
        ),
    ]
