# Generated by Django 4.2.9 on 2024-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0029_prozessentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='prozessentry',
            name='ist_abgeschlossen',
            field=models.BooleanField(default=False),
        ),
    ]
