# Generated by Django 4.2.9 on 2024-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0030_prozessentry_ist_abgeschlossen'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewboardentry',
            name='iv_heute',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
