# Generated by Django 4.2.9 on 2024-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0033_alter_dealdaten_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='genehmigt',
            field=models.BooleanField(default=False),
        ),
    ]
