# Generated by Django 4.2.9 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0034_deal_genehmigt'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewboardentry',
            name='ist_aktuell',
            field=models.BooleanField(default=True),
        ),
    ]
