# Generated by Django 4.2.9 on 2024-02-28 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0035_interviewboardentry_ist_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewboardentry',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='interviewboardentry',
            name='week_start',
        ),
        migrations.AddField(
            model_name='interviewboardentry',
            name='entry_added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
