# Generated by Django 4.2.9 on 2024-03-05 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0036_remove_interviewboardentry_week_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=200)),
                ('tool_added_at', models.DateTimeField(auto_now_add=True)),
                ('kosten', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolKostenRechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(blank=True, max_length=200, null=True)),
                ('gesamtsumme', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toolkostenrechnung_added_at', models.DateTimeField(auto_now_add=True)),
                ('toolkostenrechnung_updated_at', models.DateTimeField(auto_now=True)),
                ('bezahlt', models.BooleanField(default=False)),
                ('bezahlt_am', models.DateField(blank=True, null=True)),
                ('genehmigt', models.BooleanField(default=False)),
                ('genehmigt_am', models.DateField(blank=True, null=True)),
                ('rechnung_fuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechnung_fuer', to=settings.AUTH_USER_MODEL)),
                ('tools', models.ManyToManyField(blank=True, related_name='toolkostenrechnung', to='billerboard.tool')),
            ],
        ),
    ]
