# Generated by Django 4.2.9 on 2024-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0038_toolkostenrechnung_lexoffice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkostenrechnung',
            name='rechnungsdatum',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
