# Generated by Django 4.2.9 on 2024-03-11 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0039_toolkostenrechnung_rechnungsdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkostenrechnung',
            name='rechnungsdatum',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
