# Generated by Django 4.2.9 on 2024-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0040_alter_toolkostenrechnung_rechnungsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='kandidat_von',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='unternehmen_von',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
