# Generated by Django 4.2.9 on 2024-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0041_deal_kandidat_von_deal_unternehmen_von'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='kandidat_von',
            field=models.CharField(blank=True, choices=[('JOIN', 'Join'), ('LINKEDIN', 'LinkedIn'), ('XING', 'Xing'), ('EMPFEHLUNG', 'Empfehlung'), ('SONSTIGES', 'Sonstiges')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='unternehmen_von',
            field=models.CharField(blank=True, choices=[('COLDCALL', 'Coldcall'), ('SHOT', 'E-Mail Sequenz'), ('SNIPER', 'Sniper Shot'), ('XING', 'Xing'), ('LINKEDIN', 'LinkedIn'), ('EMPFEHLUNG', 'Empfehlung'), ('SONSTIGES', 'Sonstiges')], max_length=200, null=True),
        ),
    ]
