# Generated by Django 4.2.9 on 2024-03-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0042_alter_deal_kandidat_von_alter_deal_unternehmen_von'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='unternehmen_von',
            field=models.CharField(blank=True, choices=[('COLDCALL', 'Coldcall'), ('SHOT', 'E-Mail Sequenz'), ('SNIPER', 'Sniper Shot'), ('XING', 'Xing'), ('LINKEDIN', 'LinkedIn'), ('EMPFEHLUNG', 'Empfehlung'), ('BESTANDSKUNDE', 'Bestandskunde'), ('SONSTIGES', 'Sonstiges')], max_length=200, null=True),
        ),
    ]
