# Generated by Django 4.2.9 on 2024-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0043_alter_deal_unternehmen_von'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='kandidat_von',
            field=models.CharField(blank=True, choices=[('JOIN', 'Join'), ('LINKEDIN', 'LinkedIn'), ('XING', 'Xing'), ('EMPFEHLUNG', 'Empfehlung'), ('MARKETING', 'Marketing / Ads'), ('SONSTIGES', 'Sonstiges')], max_length=200, null=True),
        ),
    ]
