# Generated by Django 4.2.9 on 2024-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0044_alter_deal_kandidat_von'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_added_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
