# Generated by Django 4.2.9 on 2024-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0046_prozessentry_abgeschlossen_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prozessentry',
            name='lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prozessentry',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
