# Generated by Django 4.2.9 on 2024-06-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0047_prozessentry_lost_prozessentry_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_added_at', models.DateTimeField(auto_now_add=True)),
                ('offer_updated_at', models.DateTimeField(auto_now=True)),
                ('stelle', models.CharField(max_length=200)),
                ('kunde', models.CharField(blank=True, max_length=200, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ist_abgeschlossen', models.BooleanField(default=False)),
                ('abgeschlossen_am', models.DateField(blank=True, null=True)),
                ('won', models.BooleanField(default=False)),
                ('lost', models.BooleanField(default=False)),
                ('offer_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_von', to=settings.AUTH_USER_MODEL)),
                ('offer_von_zwei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_von_zwei', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
