# Generated by Django 4.2.9 on 2024-06-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0049_offer_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='kandidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billerboard.kandidat'),
        ),
    ]
