# Generated by Django 4.2.9 on 2024-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0050_offer_kandidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='kandidat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
