# Generated by Django 4.2.9 on 2024-06-06 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0051_alter_offer_kandidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_von',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer_von', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
