# Generated by Django 4.2.9 on 2024-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0052_alter_offer_offer_von'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lost_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
