# Generated by Django 4.2.9 on 2024-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0053_offer_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='bonding_mail',
            field=models.BooleanField(default=False),
        ),
    ]
