# Generated by Django 4.2.9 on 2024-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billerboard', '0055_deal_abteilung'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='storniert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='storniert_am',
            field=models.DateField(blank=True, null=True),
        ),
    ]
