# Generated by Django 4.2.9 on 2024-07-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billerboard', '0056_deal_storniert_deal_storniert_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='storniert_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storniert_von', to=settings.AUTH_USER_MODEL),
        ),
    ]
