# Generated by Django 4.2.7 on 2023-11-22 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "billerboard",
            "0005_kontakt_anrede_kontakt_doer_kontakt_eingetragen_von_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ListenImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("liste", models.FileField(max_length=500, upload_to="uploads/")),
                ("datum", models.DateTimeField(auto_now_add=True)),
                ("erfolgreich", models.BooleanField(default=False)),
                ("neue_kontakte", models.IntegerField(default=0)),
                ("neue_unternehmen", models.IntegerField(default=0)),
                ("grund", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "fuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hochgeladen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hochgeladen_von",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished", models.DateTimeField(auto_now_add=True)),
                (
                    "import_liste",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_liste",
                        to="dataentry.listenimport",
                    ),
                ),
                (
                    "unternehmen",
                    models.ManyToManyField(blank=True, to="billerboard.unternehmen"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_started", models.DateTimeField(blank=True, null=True)),
                ("time_finished", models.DateTimeField(blank=True, null=True)),
                ("skip", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kontakt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.kontakt",
                    ),
                ),
                (
                    "unternehmen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billerboard.unternehmen",
                    ),
                ),
            ],
        ),
    ]
