# Generated by Django 4.2.7 on 2023-12-04 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dataentry", "0003_alter_listenimport_liste_userrate_listassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataEntryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_skips", models.IntegerField(default=10)),
                ("lifetime_skips", models.IntegerField(default=0)),
                ("lifetime_completed", models.IntegerField(default=0)),
                ("lifetime_hold", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="skip",
            new_name="skipped",
        ),
        migrations.DeleteModel(
            name="UserRate",
        ),
        migrations.AddField(
            model_name="dataentryprofile",
            name="current_working",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataentry.entry",
            ),
        ),
        migrations.AddField(
            model_name="dataentryprofile",
            name="rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataentry.entryrate",
            ),
        ),
        migrations.AddField(
            model_name="dataentryprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataentryprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
