# Generated by Django 4.2.7 on 2023-12-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0004_dataentryprofile_rename_skip_entry_skipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="on_hold",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
