# Generated by Django 4.2.7 on 2023-12-04 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0006_remove_liste_unternehmen_liste_kontekte"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liste",
            old_name="kontekte",
            new_name="kontakte",
        ),
    ]
