# Generated by Django 4.2.7 on 2023-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0009_alter_unternehmen_options_and_more"),
        ("dataentry", "0009_alter_liste_kontakte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liste",
            name="kontakte",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="kontakte", to="billerboard.kontakt"
            ),
        ),
    ]
