# Generated by Django 4.2.7 on 2023-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billerboard", "0010_remove_unternehmen_kontakt_and_more"),
        ("dataentry", "0010_alter_liste_kontakte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liste",
            name="kontakte",
            field=models.ManyToManyField(
                blank=True, related_name="kontakte", to="billerboard.kontakt"
            ),
        ),
    ]
