# Generated by Django 4.2.7 on 2023-12-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0011_alter_liste_kontakte"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="started_at",
        ),
        migrations.AlterField(
            model_name="liste",
            name="finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
