# Generated by Django 4.2.7 on 2023-12-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0012_remove_entry_started_at_alter_liste_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="listassignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataentry.listassignment",
            ),
        ),
    ]
