# Generated by Django 4.2.7 on 2023-12-13 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0013_entry_listassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liste",
            name="kontakte",
        ),
    ]
