# Generated by Django 4.2.7 on 2023-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0014_remove_liste_kontakte"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
