# Generated by Django 4.2.7 on 2023-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0016_entry_skip_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="listassignment",
            name="offene_stellen",
            field=models.IntegerField(default=1),
        ),
    ]
